// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyNmn2eh5z9te78E-uH9YKdCVNE7BwhPk',
    appId: '1:539201075036:android:9f7898fc37ff57550df399',
    messagingSenderId: '539201075036',
    projectId: 'chat-app-6c879',
    databaseURL: 'https://chat-app-6c879-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-6c879.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJYg92h2SkJrf8phqNDcnf3Ve7C283VVs',
    appId: '1:539201075036:ios:cb98abe05f48e26b0df399',
    messagingSenderId: '539201075036',
    projectId: 'chat-app-6c879',
    databaseURL: 'https://chat-app-6c879-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-6c879.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEmjS1Pjc0xiZ6CWlrSSnkTdrcBmMIysM',
    appId: '1:539201075036:web:105bee3e41981a2b0df399',
    messagingSenderId: '539201075036',
    projectId: 'chat-app-6c879',
    authDomain: 'chat-app-6c879.firebaseapp.com',
    databaseURL: 'https://chat-app-6c879-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-6c879.appspot.com',
  );

}